<a href="https://colab.research.google.com/github/ankorn/redred/blob/main/redred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# seq2seq

In [ ]:
!pip uninstall datasets torchao

Found existing installation: datasets 3.6.0
Uninstalling datasets-3.6.0:
  Would remove:
    /usr/local/bin/datasets-cli
    /usr/local/lib/python3.12/dist-packages/datasets-3.6.0.dist-info/*
    /usr/local/lib/python3.12/dist-packages/datasets/*
Proceed (Y/n)? y
  Successfully uninstalled datasets-3.6.0
Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Would remove:
    /usr/local/lib/python3.12/dist-packages/torchao-0.10.0.dist-info/*
    /usr/local/lib/python3.12/dist-packages/torchao/*
Proceed (Y/n)? y
  Successfully uninstalled torchao-0.10.0

In [ ]:
!pip -q install datasets==3.6.0 torchao==0.16.0 evaluate rouge_score

  Preparing metadata (setup.py) ... done
  Building wheel for rouge_score (setup.py) ... done

In [ ]:
from datasets import load_dataset

dataset = load_dataset("webis/tldr-17", split="train", streaming=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "sshleifer/distilbart-cnn-6-6"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

Loading weights:   0%|          | 0/262 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [ ]:
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],  # for BART; adjust for other models
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM,
)

peft_model = get_peft_model(model, lora_config)
peft_model.print_trainable_parameters()

trainable params: 1,179,648 || all params: 334,053,376 || trainable%: 0.3531

In [ ]:
import torch
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

def preprocess_function(examples):
    model_inputs = tokenizer(
        examples["content"],
        max_length=1024, # CHECK: BART's max position embedding is 1024
        truncation=True,
        padding="max_length",
    )

    labels = tokenizer(
        examples["summary"],
        max_length=128, # TODO: CHECK
        truncation=True,
        padding="max_length",
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_dataset = dataset.map(preprocess_function, batched=True, remove_columns=dataset.column_names)

train_dataset = tokenized_dataset.shuffle().take(100000)
eval_dataset = tokenized_dataset.shuffle().take(1000)

In [ ]:
import numpy as np
import evaluate

metric = evaluate.load("rouge")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)

    # BERTScore (optional, slower)
    # from bert_score import score
    # P, R, F1 = score(decoded_preds, decoded_labels, lang="en")
    # result["bertscore"] = F1.mean().item()

    return {k: round(v, 4) for k, v in result.items()}

In [ ]:
training_args = Seq2SeqTrainingArguments(
    eval_strategy="steps",
    eval_steps=100,
    save_steps=100,
    logging_steps=100,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    predict_with_generate=True,
    generation_max_length=128,
    metric_for_best_model="eval_rouge1",
    load_best_model_at_end=True,
    max_steps=1000
)

trainer = Seq2SeqTrainer(
    model=peft_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()

KeyboardInterrupt:

In [ ]:
post = '''Why do all old people have short hair?
I’ve noticed something and I’m curious if there’s a reason behind it. Most older women I see (like 70+) tend to have short hair. I honestly can’t think of many I’ve met with long hair.
Is there a practical reason for this? Like easier maintenance, hair thinning, or just preference over time? Would love to hear from anyone who knows or has experience with this.'''

In [ ]:
model.eval()
inputs = tokenizer(post, return_tensors="pt", max_length=512, truncation=True)
summary_ids = model.generate(inputs["input_ids"], max_length=128, num_beams=4, early_stopping=True)
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print(summary)

 Most older women (like 70+) tend to have short hair . Is there a practical reason for this? Like easier maintenance, hair thinning, or just preference over time? Would love to hear from anyone who knows or has experience with this. Would like to see anyone

# chat llm

In [1]:
%pip uninstall -q -y torchao

%pip -q install -q trl evaluate datasets==3.6.0 trl==0.12.0 bitsandbytes>=0.46.1 rouge_score peft torchao==0.16.0

In [2]:
import argparse
import json
import os
import random
import re
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, PeftModel, TaskType
from trl import SFTTrainer
import evaluate
from tqdm import tqdm

In [ ]:
MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"   # ~1.1 GB Q4_K_M
# MODEL_NAME = "google/gemma-3-1b-it"       # ~600 MB Q4_K_M

MAX_SEQ_LENGTH = 1500

LORA_R = 64
LORA_ALPHA = 32
LORA_DROPOUT = 0.05

BATCH_SIZE = 8
GRAD_ACCUMULATION = 4
LEARNING_RATE = 2e-4
NUM_EPOCHS = 1
WARMUP_RATIO = 0.03

In [4]:
def clean_text(text: str) -> str:
    text = text.replace("&#x200B;", "").replace("&gt;", ">").replace("&lt;", "<")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [5]:
dataset = load_dataset("webis/tldr-17", split="train", trust_remote_code=True, streaming=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

tldr-17.py: 0.00B [00:00, ?B/s]

dataset_infos.json: 0.00B [00:00, ?B/s]

In [6]:
from pandas import DataFrame
from datasets import Dataset

dataset = Dataset.from_pandas(DataFrame(list(dataset.take(300_000))))

dataset = dataset.train_test_split(test_size=0.005)
train_ds = dataset["train"]
eval_ds = dataset["test"]

In [7]:
system_msg = (
    "You are a helpful assistant that writes concise TL;DR summaries "
    "of Reddit posts in one or two sentences."
)

def format_chat(example):
    content = clean_text(example["content"])
    summary = clean_text(example["summary"])

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": f"Reddit post:\n{content}"},
        {"role": "assistant", "content": summary},
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    return {"text": text}

In [8]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.bfloat16,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [9]:
train_ds_formatted = train_ds.map(format_chat, remove_columns=train_ds.column_names)
eval_ds_formatted  = eval_ds.map(format_chat, remove_columns=eval_ds.column_names)

Map:   0%|          | 0/298500 [00:00<?, ? examples/s]

Map:   0%|          | 0/1500 [00:00<?, ? examples/s]

In [10]:
from peft import LoraConfig, TaskType, get_peft_model

lora_cfg = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_dropout=LORA_DROPOUT,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)
model = get_peft_model(model, lora_cfg)
model.print_trainable_parameters()

trainable params: 73,859,072 || all params: 1,617,573,376 || trainable%: 4.5660

In [21]:
print(train_ds_formatted['text'][0])

<|im_start|>system
You are a helpful assistant that writes concise TL;DR summaries of Reddit posts in one or two sentences.<|im_end|>
<|im_start|>user
Reddit post:
There are some noticeable differences, such as the cleaner textures, but in terms of additional content, it's not much. There's a vault that contains all of the game audio and some art concepts from all three games as well as some DMC4 concept art. Unfortunately, however, the game does not come with better customization options. Like in-game brightness adjustments and full button mapping. There is also the fact that in DMC1 the subtitles are half-assed and not always on-screen when it should be, but that's my personal grief. I bought it a while ago and would recommend getting it if you want to have all three games on a single disc that runs better and is more easily accessible.<|im_end|>
<|im_start|>assistant
A vault with some music and art, and achievements/trophies.<|im_end|>

In [11]:
from trl import DataCollatorForCompletionOnlyLM

response_template = "<|im_start|>assistant\n"

collator = DataCollatorForCompletionOnlyLM(
    response_template=response_template, 
    tokenizer=tokenizer
)

In [12]:
training_args = TrainingArguments(
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LEARNING_RATE,
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=3,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    optim="paged_adamw_8bit",
    lr_scheduler_type="cosine",
    warmup_ratio=WARMUP_RATIO,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_ds_formatted,
    eval_dataset=eval_ds_formatted,
    args=training_args,
    max_seq_length=MAX_SEQ_LENGTH,
    packing=False, # False is safer for variable-length summaries
    data_collator=collator,
)

trainer.train()

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length. Will not be supported from version '0.13.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
/usr/local/lib/python3.12/dist-packages/trl/trainer/sft_trainer.py:300: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(

Map:   0%|          | 0/298500 [00:00<?, ? examples/s]

Map:   0%|          | 0/1500 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151645}.

/usr/local/lib/python3.12/dist-packages/trl/trainer/utils.py:160: UserWarning: Could not find response key `<|im_start|>assistant
` in the following instance: <|im_start|>system
You are a helpful assistant that writes concise TL;DR summaries of Reddit posts in one or two sentences.<|im_end|>
<|im_start|>user
Reddit post:
I've told this story a few times on Reddit... But every time I see posts about the "humane" society, I just get angry all over again... And I have to tell the story.. I'm copying and pasting from the last time I posted it.. The top part might not be relevant because i don't feel like editing. So here's the Anyone who says spending that kind of money on a dog is a waste of money can go fuck themselves.. I've been to so many funerals (way too many...) for friends and family members.. But I've never cried harder than I did when my dogs have died. That shit is just utterly devastating. I'm gonna keep this story as short as possible, but I feel it's relevant.. I told it on reddit a few years ago, but I'll tell a short version of it.. EDIT: OK.. after writing it.. it's not short.. sorry.. I rescued a dog while camping one time. I didn't feel like sleeping in a tent, and I can't sleep at night very well so I slept in my car and watched movies. Well, I was really low on gas at 3am, so I decided to go find a gas station.. I pulled in to one (it was closed..dammit) and a dog came hobbling up to me, and if she were a human, she would've been bawling her eyes out. This dog was crying, and it was obvious her back leg was broken. I happened to have a bag of chips and a bottle of water, so I gave it to her and she acted like she hadn't eaten in days. I COULD NOT leave her there.. I just couldn't. We were supposed to be leaving from the campground sometime that next day, so I said fuck it, put the dog in my car and just headed home.. We were 3 hours away.. I layed my sleeping bag on the passenger seat and put the dog on it, and petted her for a while until she fell asleep.. I FINALLY found a gas station (thank god, my car had said 0 Miles to Empty for like 30 miles.) The dog pissed in my car..twice (I had a 2006 Mustang.) But I could immediately tell that she was so insanely happy that someone was finally giving her attention.. We pulled into another closed gas station and I decided to see if the "pay at the pump" still worked. The dog jumped out and started wandering around, but when I was leaving, I just called for her and she came running back to me.. Like she'd been my dog for years. It was incredible.. I finally got her home, fed her, gave her water, and went to sleep. This dog literally followed me EVERYWHERE. She stayed literally between my legs when I walked, and slept directly under me under my bed. However.. I couldn't keep her.. I lived with my grandparents at the time and their dog (who was also my dog, and I miss him :( ) was territorial. He was NOT violent by any stretch of the imagination, he just would piss everywhere inside if any other dog was around. So the next day I took her to a no-kill rescue shelter. Even after one night I was attached to this dog like crazy and was almost in tears. They said they didn't have any room for her and that I should just keep her! I told them countless times that I COULDN'T! I would fucking love to, but I CAN'T KEEP HER! And I refused to take her to the "humane" society because they would just kill her. So they finally said take her home tonight, and they would open up a place for her tomorrow. Fucking obviously they just wanted me to get attached to the dog so I would keep her. Well, the first thing happened.. I fell in love with her! (Not in the creepy way ya bastards..) This dog worshiped me and I had truly never felt that kind of love from anyone or anything in my life.. But I still could not keep her.. I posted countless things on facebook and stuff hoping someone would take her (I was leaving that day to go out of town so I was on a very short deadline.. This is relevant) I didn't get a very good response, so I took her back to the shelter.. I sat in the waiting room bawling my eyes out because I swear the dog knew what was going on.. She was whining and licking my face. So then the guy I talked to the day before comes in and says "Oh, sorry. We have no room. Take her to the humane society." You motherfuckers.. So I said "I'm gonna tie her up right outside the door and fucking leave, then you HAVE to take her." They said "If you do that, we'll call the cops and have you arrested for animal cruelty." I was tempted to say "You don't even know who the fuck I am." but I picked the dog up, said fuck you and went on my way. I had zero choice at that point.. I was already supposed to be headed out of town, and the piece of shit at the no-kill shelter ASSURED ME that the "humane" society would keep the dog safe, and not kill her.. So.. defeated, I went to the St. Louis Fuck You "Humane" Society. I walk in with tears running down my face holding her. I tell the lady at the front desk my story, she gets up.. walks around the counter, pulls the dog out of my arms and walks the fuck away without saying a word. I'm not exaggerating by any means. I never saw the dog again and I couldn't say a word because I would've fucking lost it. So they make me fill out a form saying "You can't inquire at all anymore about this dog. Period." I resist telling them all to fuck themselves and leave.. sat in my car and bawled for about 30 minutes.. then started driving out of town.. On the way to my destination, a friend of mine whose husband is very well-off calls me and asks about the dog.. I tell her the story and she says she wants to adopt her. FANTASTIC!!! (keep fucking reading..) She calls the humane society (she already knew their number because she donated to them every month. She actually had a check in front of her that she hadn't sent yet. They tell her she has to wait a couple days until they examine the dog and shit. OK Sure.. They call her back and say her leg is broken, and it's gonna cost around $3,000 to either fix or amputate it. Seriously, same price for both. My friend was already a bit worried that her husband wouldn't go for having another dog (they already had 2, and she worships them, in her words "They get fed before I do!"), so she didn't think she'd be able to justify that cost to him. She even asked the "humane" society what her monthly donations were going towards, This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/utils.py:160: UserWarning: Could not find response key `<|im_start|>assistant
` in the following instance: <|im_start|>system
You are a helpful assistant that writes concise TL;DR summaries of Reddit posts in one or two sentences.<|im_end|>
<|im_start|>user
Reddit post:
So, I've actually got several that are all tied together. 1/13/01 there was a huge earthquake off the coast of El Salvador, where I was living. Landslides and devastation were everywhere. We had a lot of time off of school, so it was awesome. 1/20/13, I was 11yo staying with my cousin at his house, but my brother and cousin were being mean to me. I called my mom for her to pick me up, and fired up Pokemon on the Gameboy. Door bell rang, I went outside, got in her car, and she started pulling out. As she did, a car rear-ended us. NBD, right? We got out, inspected the damage, realized it wasn't much. Well, as we were realizing it wasn't too bad (nobody has insurance there)......four guys jump out with guns. At first, my mom and I thought it was a robbery. I told them they could have my Gameboy, my mom said they could keep the car and her purse. One guy moved their car beside of ours as the other three grabbed her and were in the process of forcing her into their car. Average height for a male there is 5'8", my mom is 5'11" and grew up in the South with a feisty brother....she was holding them off for a couple of minutes (I think, it's impossible to keep track of time). She begged for help from a truck load of cops across the street, they didn't move. I ran to my cousin's house and beat on the door begging for help. None came. I went back and hit the leader with my Gameboy as hard as I could. They had just switched from shoving her into their car to shoving her into our car. I could tell she was giving out. The guy that I hit stumbled for a second, then swung the gun at me. To this day, I can see the 38 special in the barrel of that snub nose. As the hammer drew back, somebody across the street fired a shot. Turns out, he heard the commotion and sprinted back to see what it was. Once he found cover, he fired into the air hoping they'd drop her. They did. I dragged my mom from the driver's seat of our car through the passenger-side door and covered her as the short gunfight elapsed (lost track of time again, could've been hours, could've been seconds). Right after the last of the bullets flew (and bullets were lodged inches from my head), the man that fired the warning shot came over to see if we were fine, but ran away immediately after because he owned his gun illegally (impossible to get legal guns there). I wish I could thank him, he saved my mom's life. The cops finally came over. and started investigating the incident. My mom kicked the bottom of the door of their car in her fight, and had a welt no-kidding the size of an egg on her left foot. Her shoes were in the middle of the street, and I went and picked them up. We were both shaking so badly I couldn't see straight. I told my brother, we called my dad. He made an hour drive in 20minutes and, in fact, beat the "backup" cops. We went home, my dad went to work the next morning like always (Saturday they work half days there). He came home crazy early, kicked open the front door, and informed us that we were leaving the house in five minutes and to be packed and IN THE CAR by then. We made an hour drive in another twenty minutes. My dad was on practically every sidewalk from our house to the airport. We filed a flight report to somewhere in South America, flew to Guatemala and landed. The kidnappers were sure to have people at the airport in El Salvador so they'd be waiting. Once in Guatemala, we caught a plane back to the states. I packed the N64, duh, while my brother packed sweats and pajamas. We got back to the states and we were all wearing hot-weather clothing while it was WELL below freezing outside. We spent over 6 months in the US and then moved back down there. We found out it was one of my Aunts who had hired (cops) kidnappers to get my mom. My Aunt had been having an affair, skimming off family company funds, and finally stolen enough that they were noticing. The plan was to kidnap my mom and pay the company back with some of the ransom money. The reason we left in a hurry the next day was because she sent an e-mail to my dad saying they knew where we lived, they knew my dog, they knew our schedule, and that they were going to kidnap all of us and rape my mom to death in front of us (brother: 9, dad, me) and then torture us to death in front of my dad, before killing him. My uncle found out about the kidnapping and was going to stay with my aunt, found out about the affair, and was still probably staying, but the theft is what caused them to get a divorce. My Aunt's first cousin was the VP of the country at the time, so he covered up all of the evidence in the case. The cops got off the hook. She's living a (much less affluent) life with visitation rights to see her daughter and nothing grievously wrong like that whore deserves. I swear to you, if I saw her tomorrow I'd beat her until she begged for death....and then grant it to her. She caused an unbelievable amount of pain for my family, things we're still struggling to get over. I've been through 5 years of therapy, my parents through like 8 years of personal therapy and 5 years of couple's therapy. The VP told my dad to sit tight as they gathered information on my Aunt, so he had to eat 2 meals a week with her until they gathered enough evidence. Well, as Americans....clearly the US Embassy helped out, right? Right? Nope. The Ambassador at the time was about to get promoted and the kidnapping of a US Citizen would've made her look bad, so they ignored it and officially called it a "lie." Rumor persisted that my mom was a black belt in like 7 martial arts (depending on who you asked) and beat the kidnappers senseless. So, it gets better. Remember the cops? Well, when I was 15, they see me on the street one day and draw guns. I recognize one of them (the one I struck with my Gameboy) and they started chasing after me. I drove through a few neighborhoods, malls, and weird roads hoping they couldn't keep up with me (they were driving a pickup, I was in a BMW 325i). They did. I don't know how I got there, but we were in this weird section of town that had this HUGE "jump" thing (ridiculously steep hill) that I was familiar with. This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/utils.py:160: UserWarning: Could not find response key `<|im_start|>assistant
` in the following instance: <|im_start|>system
You are a helpful assistant that writes concise TL;DR summaries of Reddit posts in one or two sentences.<|im_end|>
<|im_start|>user
Reddit post:

KeyboardInterrupt:

In [ ]:
import huggingface_hub

huggingface_hub.login()

In [ ]:
model.push_to_hub("pameydorke/redred-qwen2.5-1.5-lora")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 45.7kB / 73.9MB

CommitInfo(commit_url='https://huggingface.co/pameydorke/redred-summarizer/commit/3e3a1d9f0882ab944d3a16ba28365306489c7af8', commit_message='Upload model', commit_description='', oid='3e3a1d9f0882ab944d3a16ba28365306489c7af8', pr_url=None, repo_url=RepoUrl('https://huggingface.co/pameydorke/redred-summarizer', endpoint='https://huggingface.co', repo_type='model', repo_id='pameydorke/redred-summarizer'), pr_revision=None, pr_num=None)

In [ ]:
model.eval()

im_end_id = tokenizer.convert_tokens_to_ids("<|im_end|>")

rouge = evaluate.load("rouge")
predictions, references = [], []

eval_subset = eval_ds.shuffle(seed=42).select(range(min(15, len(eval_ds))))

for example in tqdm(eval_subset, desc="Generating summaries"):
    content = clean_text(example["content"])
    ref = clean_text(example["summary"])

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": f"Reddit post:\n{content}"},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            num_beams=4,
            early_stopping=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=[tokenizer.eos_token_id, im_end_id],
            length_penalty=1,
            # no_repeat_ngram_size=3,
        )
        
    pred = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1] :], skip_special_tokens=True
    ).strip()

    predictions.append(pred)
    references.append(ref)

results = rouge.compute(
    predictions=predictions,
    references=references,
    use_stemmer=True,
)

for k, v in results.items():
    print(f"  {k}: {v:.4f}")

Generating summaries: 100%|██████████| 15/15 [02:34<00:00, 10.29s/it]

  rouge1: 0.1383
  rouge2: 0.0287
  rougeL: 0.0927
  rougeLsum: 0.0932

In [33]:
# length_penalty=0.8; no_repeat_ngram_size=None

print(predictions[0], '\n', references[0], '\n')
# print(predictions[42], '\n', references[42], '\n')
print(predictions[13], '\n', references[13], '\n')
print(predictions[11], '\n', references[11], '\n')
# print(predictions[39], '\n', references[39], '\n')

K-mart sucks. Edit: I'm sorry, I forgot to mention that I was in the women's section. The men's section was just as bad. Edit 2: It's not just me. I've seen this happen at other K-marts too. EDIT 3: I don't know if
 Shopping at K-mart is like going back in time to the USSR.

Rockstar North will continue to use this technique because it works. Other studios will use it too. Rockstar North is not the only studio that uses this technique. GTA 4 was the first game to use it. GTA V will be the second. GTA VI will probably be the third. GTA VII might be the
 Tech is already developed, things get cheaper (especially cameras)

Lannisters are the only ones who can stop him, and they don't seem to want to. Edit: Also, I'm not sure if this is the right place to ask this question, but is there a reason why the Lannister family doesn't want to stop him? Is it because they're afraid
 He's Captain of the Kingsguard, and a Lannister at that, he can basically do whatever he pleases.

In [ ]:
# initial: rouge1: 0.1373
# after 500 steps: rouge1: 0.1062

In [20]:
print(predictions[0], '\n', references[0], '\n')
print(predictions[42], '\n', references[42], '\n')
print(predictions[13], '\n', references[13], '\n')
print(predictions[11], '\n', references[11], '\n')
print(predictions[39], '\n', references[39], '\n')

Zarek saved us from the brink on the last turn. We almost lost due to an absence of food, but Zarek's once-a-game saved us from the brink on the last turn. We almost lost due to an absence of food, but Zarek's once-a-game saved us from the brink on the last turn. We almost lost due to an absence of food, but Zarek's once-a-game saved us from the brink on the last turn. We almost lost due to an absence of food, but Zarek's once-a-game saved us from the brink on the last turn. We almost lost
 Zarek's finest moment, and why you should give a second thought to protestors

I own a home. It isn't particularly large. It's two stories, maybe 3 or 4 bedrooms. I live far enough from the city that my neighbors' homes are not right up against mine, but close enough that I can drive there without too much trouble. It's a smaller town, but has everything I need in it. It is on the west coast, and the beach is nearby. Perhaps a 20 minute drive. There is almost no grass on the front. Just a cobbestone path to the raised wooden porch, which has a seating area. There are flower beds to each side, filled with
 Own a home and make it mine

GIMP is a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop replacement. It's not a Photoshop replacement because it's a Photoshop
 you're right about GIMP being a viable alternative to Photoshop for amateurs and hobbyists to make digital doodles. But your opinion doesn't apply to any of the people complaining here.

He's not fat, he's just got a lot of weight on his shoulders at the moment. It's not his fault, he's just trying to get back to his normal self. I hope he can resolve it, if not, I feel for him as it's a horrible situation to be put in. If it's an internal mistake, then I feel sorry for them as if it's not recoverable then they've killed a potentially huge company. I used gox as it was the nicest of the exchanges for trading (everything displayed on one page and had great trade history keeping) and had a good API too. Saying
 I feel for him :( But damn they should of kept better care of the coins!!

If you're a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female and you're a guy, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female, get a write-away. If you're not a hot female
 As much as it sucks & isn't fair, pay it, because the black mark of being a possible thief puts your whole job at risk, it's not worth it.

In [ ]:
rouge = evaluate.load("rouge")
predictions, references = [], []

for example in tqdm(eval_subset):
    content = example["content"]   # keep raw; clean_text was not shown, apply if safe
    ref = example["summary"]

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": f"Reddit post:\n{content}"},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            num_beams=1,               # simpler, greedy
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    pred = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True,
    ).strip()

    if pred.startswith("assistant\n"):
        print('>>>', 'assistant on pred')
        pred = pred[len("assistant\n"):]

    if "<|im_end|>" in pred:
        print('>>>', '<|im_end|> on pred')
        pred = pred.replace("<|im_end|>", "").strip()

    predictions.append(pred)
    references.append(ref)

100%|██████████| 100/100 [08:03<00:00,  4.84s/it]

In [1]:
predictions[42], references[42]

NameError: name 'predictions' is not defined

In [ ]:
# 1. Merge LoRA into base model (do this before ONNX export)
merged_model = model.merge_and_unload()

# 2. Save merged model temporarily
import tempfile, os
temp_dir = tempfile.mkdtemp()
merged_model.save_pretrained(temp_dir)
tokenizer.save_pretrained(temp_dir)

# 3. Export to ONNX using Optimum
!pip install -q optimum[onnxruntime]

from optimum.onnxruntime import ORTModelForCausalLM
from transformers import AutoTokenizer

onnx_temp = tempfile.mkdtemp()

# Export with cache for efficient inference
ort_model = ORTModelForCausalLM.from_pretrained(
    temp_dir,
    export=True,
    provider="CUDAExecutionProvider",  # or "CPUExecutionProvider"
    use_cache=True,
)

ort_model.save_pretrained(onnx_temp)
tokenizer.save_pretrained(onnx_temp)

# 4. Push to Hugging Face Hub
from huggingface_hub import HfApi, create_repo

repo_id = "pameydorke/redred-qwen2.5-1.5-lora-onnx" 
create_repo(repo_id, exist_ok=True, repo_type="model")

api = HfApi()
api.upload_folder(
    folder_path=onnx_temp,
    repo_id=repo_id,
    repo_type="model",
)

print(f"Pushed to https://huggingface.co/{repo_id}")

In [24]:
model.eval()

post_text = '''Why does Black Pepper get the place of honor next to Salt?
Salt is a substance that is literally necessary to keep us alive. Because of that, it makes sense that it is one of the five tastes that our tounge is able to detect. it basically just makes meat taste better on like an evolutionary level.

And then the thing that is always said in the same breath is just a seemingly random spice made from spicy ground up seeds or something. I assume that not all cultures value black pepper the same as we do in the west. But since it doesnt have the organic significance that salt does, I assume it could be any spicy thing we pair with salt. Why is it specifically black pepper?
'''

messages = [
    {"role": "system", "content": "Write a concise TL;DR summary of the Reddit post."},
    {"role": "user", "content": f"Reddit post:\n{post_text}"},
]
prompt = tokenizer.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=64,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        pad_token_id=tokenizer.pad_token_id,
    )

summary = tokenizer.decode(
    outputs[0][inputs.input_ids.shape[1] :], skip_special_tokens=True
).strip()

summary

"Black pepper is not necessarily more flavorful than other spices because its flavor profile isn't particularly unique. The flavor profile of black pepper would probably be similar to cinnamon and cloves if you were to try them out yourself. They are both sweet, warm, and slightly spicier. So maybe they're not so different after all"

In [ ]:
adapted_path = 'https://huggingface.co/pameydorke/redred-summarizer'

In [ ]:
# (?)

peft_model = PeftModel.from_pretrained(base_model, adapter_path)
merged_model = model.merge_and_unload()

from transformers import AutoModelForCausalLM
merged = AutoModelForCausalLM.from_pretrained("./tldr-lora-final")
merged.save_pretrained("./tldr-merged")

# 3. Convert to GGUF (install llama.cpp, then)
python convert_hf_to_gguf.py ./tldr-merged --outfile tldr-qwen-1.5b-q4_k_m.gguf --outtype q4_k_m

In [ ]:
# Merge your LoRA adapter into the base Qwen2.5-1.5B-Instruct.
# Export the merged model to ONNX with optimum-cli :
!optimum-cli export onnx --model ./tldr-merged ./tldr-onnx/
# Quantize for the browser:
!optimum-cli onnxruntime quantize --onnx_model ./tldr-onnx/ -o ./tldr-onnx-q4/

# JavaScript
# import { pipeline } from "@huggingface/transformers";
# const generator = await pipeline(
#   "text-generation",
#   "your-username/tldr-qwen-onnx",
#   { dtype: "q4", device: "webgpu" }
# );